### ISSUE TITLE
performance improvement: avoid slow down when 1 node disconnects

### ISSUE THREAD

**Issue by freddyrios** [copenhagenatomics/dotNext#4]
This was tested with the big struct example with fast writes rebased on the latest develop branch (25th of jan).

The test involved removing the ethernet cable to one of the nodes and seeing the impact on cluster speed to process 1k entries. In the test it went from 1k entries in 2 seconds to 18 seconds (and remained that way).

**Comment by sakno** [comment]
`ConnectTimeout` added back to the configuration. Now it can be used to reduce the impact caused by disconnected node.

**Comment by freddyrios** [comment]
confirmed fixed by testing it with 5 ms connection timeouts.
